databases:
  - name: tankore-db
    plan: free
    databaseName: tankore
    user: tankore

services:
  - type: web
    name: tankore
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: DATABASE_URL
        fromDatabase:
          name: tankore-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
