# Generated by Django 5.2.7 on 2025-12-19 03:11
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='wordBookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_wordbooks', to=settings.AUTH_USER_MODEL)),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.wordbook')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'wordbook'], name='home_wordbo_user_id_bfe22a_idx')],
                'unique_together': {('user', 'wordbook')},
            },
        ),
    ]
