# Generated by Django 5.2.7 on 2025-12-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_wordbookbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='wordbookbookmark',
            new_name='home_wordbo_user_id_b9a005_idx',
            old_name='home_wordbo_user_id_1c80c6_idx',
        ),
        migrations.AddField(
            model_name='wordbook',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='wordbooks', to='home.tag'),
        ),
    ]
