# Generated by Django 5.2.7 on 2025-12-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbook',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
