# Generated by Django 5.2.7 on 2025-12-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tag_wordbook_tags'),
    ]

    operations = [
    ]
