# Generated by GitHub Copilot
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


def gen_unique_slug(model, base, max_len=60):
    base_slug = slugify(base)[:max_len]
    slug = base_slug
    i = 1
    while model.objects.filter(slug=slug).exists():
        suffix = f"-{i}"
        slug = (base_slug[: max_len - len(suffix)]) + suffix
        i += 1
    return slug


def forwards(apps, schema_editor):
    Tag = apps.get_model('home', 'Tag')
    # Ensure created/updated timestamps are set if missing
    now = timezone.now()
    for tag in Tag.objects.all():
        if not getattr(tag, 'created_at', None):
            tag.created_at = now
        if not getattr(tag, 'updated_at', None):
            tag.updated_at = now
        # Populate slug if empty
        if not getattr(tag, 'slug', None):
            tag.slug = gen_unique_slug(Tag, tag.name)
        tag.save(update_fields=['created_at', 'updated_at', 'slug'])


def backwards(apps, schema_editor):
    # No-op safe backwards
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_tag_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
