# Generated by Django 5.2.7 on 2025-12-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprofile'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='background_color',
                    field=models.CharField(default='#fffff0', max_length=7),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunSQL(
            sql="UPDATE home_userprofile SET background_color = '#fffff0' WHERE background_color IS NULL OR background_color = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
