# Generated by Django 5.2.7 on 2025-12-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userprofile_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='avatar_image',
            field=models.CharField(choices=[('account.png', 'Account 1'), ('account2.png', 'Account 2'), ('account3.png', 'Account 3'), ('account4.png', 'Account 4'), ('account5.png', 'Account 5'), ('account6.png', 'Account 6')], default='account.png', max_length=100, verbose_name='アバター画像'),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='background_color',
            field=models.CharField(choices=[('#fffff0', 'Ivory'), ('#e3d7a3', 'Beige'), ('#d8f3dc', 'Light Green'), ('#f8d7da', 'Light Red'), ('#dbeafe', 'Light Blue'), ('#fef3c7', 'Light Yellow'), ('#e0f2fe', 'Sky Blue')], default='#fffff0', max_length=7, verbose_name='背景色'),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='AI生成'),
        ),
    ]
