# Generated by Django 5.2.7 on 2025-12-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_wordbook_avatar_image_wordbook_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.CharField(choices=[('account.png', 'Account 1'), ('account2.png', 'Account 2'), ('account3.png', 'Account 3'), ('account4.png', 'Account 4'), ('account5.png', 'Account 5'), ('account6.png', 'Account 6'), ('account7.png', 'Account 7'), ('account8.png', 'Account 8')], default='account.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='avatar_image',
            field=models.CharField(choices=[('account.png', 'Account 1'), ('account2.png', 'Account 2'), ('account3.png', 'Account 3'), ('account4.png', 'Account 4'), ('account5.png', 'Account 5'), ('account6.png', 'Account 6'), ('account7.png', 'Account 7'), ('account8.png', 'Account 8')], default='account.png', max_length=100, verbose_name='アバター画像'),
        ),
    ]
