# Generated by Django 5.2.7 on 2025-12-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_userprofile_avatar_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbook',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='wordbook',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='wordbook',
            name='is_ai_generated',
        ),
    ]
