# Generated by Django 5.2.7 on 2025-12-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_wordbook_avatar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='カスタムアバター画像'),
        ),
    ]
