# Generated by Django 5.2.7 on 2025-12-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_userprofile_custom_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='avatar_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
