# Generated by Django 5.2.7 on 2025-12-25 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_wordbook_avatar_image_wordbook_background_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCardStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_cards', to=settings.AUTH_USER_MODEL)),
                ('wordcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='home.wordcard')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'wordcard'], name='home_wordca_user_id_c30254_idx')],
                'unique_together': {('user', 'wordcard')},
            },
        ),
    ]
