# Generated by Django 5.2.7 on 2025-12-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_wordcardstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='ピン留め（おすすめ）'),
        ),
    ]
