# Generated by Django 5.2.7 on 2026-01-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_wordbook_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
