# Generated by Django 5.2.7 on 2026-01-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.CharField(default='https://api.dicebear.com/7.x/avataaars/svg?seed=Felix', max_length=500),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='avatar_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
