# Generated by Django 5.2.7 on 2026-01-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_userprofile_avatar_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbook',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='wordbook',
            name='background_color',
        ),
        migrations.AddField(
            model_name='wordbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='wordbook_covers/', verbose_name='表紙画像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.CharField(choices=[('account.png', 'Account 1'), ('account2.png', 'Account 2'), ('account3.png', 'Account 3'), ('account4.png', 'Account 4'), ('account5.png', 'Account 5'), ('account6.png', 'Account 6'), ('account7.png', 'Account 7'), ('account8.png', 'Account 8')], default='account.png', max_length=100),
        ),
    ]
