# Generated by Django 5.2.7 on 2026-01-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_wordbook_avatar_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbook',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='wordbook',
            name='avatar_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
